import type { Metadata } from "next";
import { Space_Grotesk, Mohave } from "next/font/google";  // Замість Geist і Geist_Mono
import "../styles/globals.css";

// Використовуємо Space Grotesk і Mohave
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const mohave = Mohave({
  variable: "--font-mohave",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${mohave.variable} antialiased`}  // Додаємо змінні шрифтів
      >
        {children}
      </body>
    </html>
  );
}
